logging:
  level:
    root: debug
    vn.ptit.moviebooking: debug
  charset:
    console: UTF-8
    file: UTF-8
  # Custom properties to define logs file paths according to different profiles
  file-path: mnt/logs

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 5  # Heartbeat frequency
    lease-expiration-duration-in-seconds: 60  # Expiration time if no heartbeat received
    instanceId: ${spring.application.name}:${server.port}
