spring:
  application:
    name: api-gateway
  profiles:
    active: "@profiles.active@"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # Automatically create routes from service discovery
          lower-case-service-id: true
      routes:
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/api/customers/**
          filters:
            - RewritePath=/api/customers/(?<segment>.*), /api/customers/${segment}

        - id: movie-service
          uri: lb://movie-service
          predicates:
            - Path=/api/movies/**
          filters:
            - RewritePath=/api/movies/(?<segment>.*), /api/movies/${segment}

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/notifications/**
          filters:
            - RewritePath=/api/notifications/(?<segment>.*), /api/notifications/${segment}

        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/payments/**
          filters:
            - RewritePath=/api/payments/(?<segment>.*), /api/payments/${segment}

        - id: seat-availability-service
          uri: lb://seat-availability-service
          predicates:
            - Path=/api/seats/availabilities/**
          filters:
            - RewritePath=/api/seats/availabilities/(?<segment>.*), /api/seats/availabilities/${segment}

        - id: ticket-booking-service
          uri: lb://ticket-booking-service
          predicates:
            - Path=/api/tickets/booking/**
          filters:
            - RewritePath=/api/tickets/booking/(?<segment>.*), /api/tickets/booking/${segment}

  lifecycle:
    timeout-per-shutdown-phase: 10s

management:
  endpoints:
    web:
      exposure:
        include: gateway,health,info
  endpoint:
    health:
      show-details: always

server:
  port: 8080
  shutdown: graceful
