
spring:
  application:
    name: movie-service
  profiles:
    active: "@profiles.active@"

  jpa:
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: false
        jdbc:
          time_zone: UTC
          ddl-auto: validate
        hibernate:
          # Hibernate only checks if the current schema matches the entity
          # If it does not match, the application will not start
          # Do not make any changes to the schema
          ddl-auto: validate
  sql:
    init:
      mode: never

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
