logging:
  level:
    root: info
    vn.ptit.moviebooking: info
    org.hibernate.sql: info
  charset:
    console: UTF-8
    file: UTF-8
  # Custom properties to define logs file paths according to different profiles
  file-path: /mnt/logs

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: root
    password: root

  jpa:
    properties:
      hibernate:
        show_sql: false

server:
  port: 8080
