spring:
  application:
    name: eureka-server
  profiles:
    active: "@profiles.active@"

server:
  port: 8761

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
