logging:
  level:
    root: debug
    vn.ptit.moviebooking: debug
  charset:
    console: UTF-8
    file: UTF-8
  # Custom properties to define logs file paths according to different profiles
  file-path: mnt/logs

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hdv_notification?serverTimezone=UTC
    username: admin_hdv_notification
    password: 123456a@

  jpa:
    properties:
      hibernate:
        show_sql: true

server:
  port: 8102

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 30  # Heartbeat sending frequency
    instanceId: ${spring.application.name}:${server.port}
